version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@4.1.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: FE install
          command: |
            npm run frontend:install

      - run:
          name: BE install
          command: |
            npm run backend:install

      - run:
          name: FE build
          command: |
            npm run frontend:build
      - run:
          name: BE build
          command: |
            npm run backend:build

      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
