version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  # different jobs are calles later in the workflows sections
  aws-cli: circle/aws-cli@1.3.1
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      # install dependencies in both apps
      - run:
          name: FE install
          command: |
            npm run frontend:install

      - run:
          name: BE install
          command: |
            npm run backend:install

      - run:
          name: FE build
          command: |
            npm run frontend:build
      - run:
        name: BE build
        command: |
          npm run backend:build
